# Generated by Django 3.2.7 on 2021-11-10 17:58

import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_name', models.CharField(max_length=50)),
                ('part_number', models.CharField(max_length=30)),
                ('valid_from', models.DateField(verbose_name='validation date')),
                ('is_valid', models.BooleanField(default=False)),
                ('requalification', models.DateField(verbose_name=models.DateField(verbose_name='validation date'))),
            ],
        ),
        migrations.CreateModel(
            name='Subassembly',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_number', models.CharField(max_length=50)),
                ('part_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Supplier_T1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('valid_from', models.DateField()),
                ('is_9001', models.BooleanField(default=False)),
                ('is_17494', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Supplier_T2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_t1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SQA.supplier_t1')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Supplier_T3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_t1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SQA.supplier_t1')),
                ('supplier_t2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SQA.supplier_t2')),
            ],
        ),
        migrations.CreateModel(
            name='PPAP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=5)),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SQA.part')),
            ],
        ),
        migrations.AddField(
            model_name='part',
            name='subassy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SQA.subassembly'),
        ),
        migrations.AddField(
            model_name='part',
            name='supplier_t1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SQA.supplier_t1'),
        ),
    ]
