# Generated by Django 3.2.7 on 2021-11-11 10:39

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('SQA', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ppap',
            name='validated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='supplier_t2',
            name='name',
            field=models.CharField(default='Tier2 Supplier', max_length=60, unique=True),
        ),
        migrations.AddField(
            model_name='supplier_t3',
            name='name',
            field=models.CharField(default='Tier3 Supplier', max_length=60, unique=True),
        ),
        migrations.AlterField(
            model_name='part',
            name='part_name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='supplier_t1',
            name='name',
            field=models.CharField(default='Tier1 Supplier', max_length=60, unique=True),
        ),
        migrations.AlterField(
            model_name='supplier_t1',
            name='valid_from',
            field=models.DateField(verbose_name=datetime.datetime(2021, 11, 11, 10, 39, 56, 219592, tzinfo=utc)),
        ),
    ]
