# Generated by Django 3.2.7 on 2021-11-11 12:56

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('SQA', '0002_auto_20211111_1139'),
    ]

    operations = [
        migrations.AddField(
            model_name='subassembly',
            name='name',
            field=models.CharField(default='Subassembly name', max_length=60, unique=True),
        ),
        migrations.AlterField(
            model_name='part',
            name='subassy',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='SQA.subassembly'),
        ),
        migrations.AlterField(
            model_name='supplier_t1',
            name='valid_from',
            field=models.DateField(verbose_name=datetime.datetime(2021, 11, 11, 12, 56, 35, 548475, tzinfo=utc)),
        ),
    ]
