# Generated by Django 3.2.7 on 2021-11-11 13:05

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('SQA', '0003_auto_20211111_1356'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='part',
            name='requalification',
        ),
        migrations.AlterField(
            model_name='supplier_t1',
            name='valid_from',
            field=models.DateField(verbose_name=datetime.datetime(2021, 11, 11, 13, 5, 13, 669726, tzinfo=utc)),
        ),
    ]
