# Generated by Django 3.2.7 on 2021-11-12 09:42

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('SQA', '0006_auto_20211112_1041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claim',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 12, 9, 42, 21, 435912, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='supplier_t1',
            name='valid_from',
            field=models.DateField(verbose_name=datetime.datetime(2021, 11, 12, 9, 42, 21, 433988, tzinfo=utc)),
        ),
    ]
