# Generated by Django 3.2.7 on 2021-11-12 10:46

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('SQA', '0008_auto_20211112_1057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claim',
            name='created',
            field=models.DateTimeField(verbose_name=datetime.datetime(2021, 11, 12, 10, 46, 5, 713559, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='claim',
            name='supplier_t1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SQA.supplier_t1'),
        ),
        migrations.AlterField(
            model_name='supplier_t1',
            name='valid_from',
            field=models.DateField(verbose_name=datetime.datetime(2021, 11, 12, 10, 46, 5, 711575, tzinfo=utc)),
        ),
    ]
