# Generated by Django 3.2.7 on 2021-11-12 10:54

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('SQA', '0009_auto_20211112_1146'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='is_produced',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='claim',
            name='created',
            field=models.DateTimeField(verbose_name=datetime.datetime(2021, 11, 12, 10, 54, 21, 339802, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='supplier_t1',
            name='valid_from',
            field=models.DateField(verbose_name=datetime.datetime(2021, 11, 12, 10, 54, 21, 337776, tzinfo=utc)),
        ),
    ]
