# Generated by Django 3.2.7 on 2021-11-12 10:59

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('SQA', '0010_auto_20211112_1154'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='revision',
            field=models.CharField(default='0', max_length=10),
        ),
        migrations.AlterField(
            model_name='claim',
            name='created',
            field=models.DateTimeField(verbose_name=datetime.datetime(2021, 11, 12, 10, 59, 16, 556148, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='part',
            name='valid_from',
            field=models.DateField(null=True, verbose_name='validation date'),
        ),
        migrations.AlterField(
            model_name='supplier_t1',
            name='valid_from',
            field=models.DateField(verbose_name=datetime.datetime(2021, 11, 12, 10, 59, 16, 554124, tzinfo=utc)),
        ),
    ]
