# Generated by Django 3.2.7 on 2021-11-12 11:00

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('SQA', '0011_auto_20211112_1159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claim',
            name='created',
            field=models.DateTimeField(verbose_name=datetime.datetime(2021, 11, 12, 11, 0, 55, 966842, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='part',
            name='valid_from',
            field=models.DateField(blank=True, null=True, verbose_name='validation date'),
        ),
        migrations.AlterField(
            model_name='supplier_t1',
            name='valid_from',
            field=models.DateField(verbose_name=datetime.datetime(2021, 11, 12, 11, 0, 55, 964801, tzinfo=utc)),
        ),
    ]
