# Generated by Django 3.2.7 on 2021-11-12 11:18

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('SQA', '0013_auto_20211112_1213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claim',
            name='created',
            field=models.DateTimeField(verbose_name=datetime.datetime(2021, 11, 12, 11, 18, 9, 163510, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='supplier_t1',
            name='valid_from',
            field=models.DateField(verbose_name=datetime.datetime(2021, 11, 12, 11, 18, 9, 161386, tzinfo=utc)),
        ),
    ]
