# Generated by Django 3.2.7 on 2021-11-12 11:48

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('SQA', '0017_auto_20211112_1243'),
    ]

    operations = [
        migrations.AddField(
            model_name='ppap',
            name='number',
            field=models.CharField(default='PPAP -supplier_name- -part_number- -revision- -date-', max_length=100),
        ),
        migrations.AlterField(
            model_name='claim',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 12, 11, 48, 28, 893024, tzinfo=utc), verbose_name='Claim date'),
        ),
        migrations.AlterField(
            model_name='supplier_t1',
            name='valid_from',
            field=models.DateField(default=datetime.datetime(2021, 11, 12, 11, 48, 28, 890839, tzinfo=utc), verbose_name='Supplier validated on'),
        ),
    ]
