# Generated by Django 3.2.7 on 2021-11-12 12:01

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('SQA', '0019_auto_20211112_1259'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ppap',
            name='is_produced',
        ),
        migrations.AddField(
            model_name='part',
            name='is_produced',
            field=models.BooleanField(default=False, verbose_name='Is in production'),
        ),
        migrations.AlterField(
            model_name='claim',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 12, 12, 1, 23, 706098, tzinfo=utc), verbose_name='Claim date'),
        ),
        migrations.AlterField(
            model_name='supplier_t1',
            name='valid_from',
            field=models.DateField(default=datetime.datetime(2021, 11, 12, 12, 1, 23, 704063, tzinfo=utc), verbose_name='Supplier validated on'),
        ),
    ]
