# Generated by Django 3.2.7 on 2021-11-12 12:07

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('SQA', '0020_auto_20211112_1301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claim',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 12, 12, 7, 19, 361031, tzinfo=utc), verbose_name='Claim date'),
        ),
        migrations.RemoveField(
            model_name='part',
            name='ppap',
        ),
        migrations.AddField(
            model_name='part',
            name='ppap',
            field=models.ManyToManyField(default=None, null=True, to='SQA.PPAP'),
        ),
        migrations.AlterField(
            model_name='supplier_t1',
            name='valid_from',
            field=models.DateField(default=datetime.datetime(2021, 11, 12, 12, 7, 19, 358541, tzinfo=utc), verbose_name='Supplier validated on'),
        ),
    ]
