# Generated by Django 3.2.7 on 2021-11-12 12:07

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('SQA', '0021_auto_20211112_1307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claim',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 12, 12, 7, 38, 788568, tzinfo=utc), verbose_name='Claim date'),
        ),
        migrations.AlterField(
            model_name='part',
            name='ppap',
            field=models.ManyToManyField(default=None, to='SQA.PPAP'),
        ),
        migrations.AlterField(
            model_name='supplier_t1',
            name='valid_from',
            field=models.DateField(default=datetime.datetime(2021, 11, 12, 12, 7, 38, 786092, tzinfo=utc), verbose_name='Supplier validated on'),
        ),
    ]
