# Generated by Django 3.2.7 on 2021-11-14 14:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('SQA', '0024_auto_20211112_1413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claim',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Claim date'),
        ),
        migrations.AlterField(
            model_name='supplier_t1',
            name='valid_from',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Supplier validated on'),
        ),
    ]
