# Generated by Django 3.2.7 on 2021-11-14 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SQA', '0025_auto_20211114_1539'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ppap',
            name='is_valid',
        ),
        migrations.RemoveField(
            model_name='ppap',
            name='valid_from',
        ),
    ]
