# Generated by Django 3.2.7 on 2021-11-14 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SQA', '0026_auto_20211114_1626'),
    ]

    operations = [
        migrations.AddField(
            model_name='ppap',
            name='valid_from',
            field=models.DateField(blank=True, null=True, verbose_name='validation date'),
        ),
    ]
