# Generated by Django 3.2.7 on 2021-11-28 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SQA', '0029_auto_20211128_2103'),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='D3_on_time',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='claim',
            name='D6_on_time',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='claim',
            name='D8_on_time',
            field=models.BooleanField(default=True),
        ),
    ]
