# Generated by Django 3.2.7 on 2021-11-29 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SQA', '0030_auto_20211128_2113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claim',
            name='number',
            field=models.CharField(blank=True, max_length=10, unique=True),
        ),
    ]
